input_dir: ../Resources
output_dir: .
fonts:
  paths: ./Fonts
  templateName: swift4
  output: ./Fonts.swift
  params:
    publicAccess: true
strings:
  paths: ./Strings/en.lproj/Localizable.strings
  templateName: structured-swift4
  output: ./Strings.swift
  params:
    publicAccess: true
xcassets:
  paths: ./Images.xcassets
  templateName: swift4
  output: ./Images.swift
  params:
    publicAccess: true
colors:
  paths: ./Colors.json
  templateName: swift4
  output: ./Colors.swift
  params:
    publicAccess: true